# Generated by Django 4.2.3 on 2023-07-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('is_active', models.BooleanField(default=False)),
                ('banner', models.ImageField(upload_to='banners', verbose_name='banner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.bannercollectionmodel', verbose_name='collection')),
            ],
        ),
    ]
