# Generated by Django 4.2.3 on 2023-07-31 13:57

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='products.categorymodel'),
        ),
    ]
