# Generated by Django 4.2.3 on 2023-08-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productwishlistmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productwishlistmodel',
            options={'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlists'},
        ),
    ]
